import { IRestaurant } from "../interfaces/IRestaurant";
// import { dishes } from "./DishesDB";

// export const restaurants: IRestaurant[] = [
//     {
//         name: "Claro",
//         chef: "Ran Shmueli",
//         imageURI: "/assets/restaurant-assets/claro.svg",
//         rating: 4,
//         popularity: 20,
//         DateOpened: new Date(2022, 11, 10),
//         openingHour: [[{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 18, minutes: 20 }, { hours: 22, minutes: 20 }]],
//         dishes: [dishes[0], dishes[1]]
//     },
//     {
//         name: "Lumina",
//         chef: "Meir Adoni",
//         imageURI: "/assets/restaurant-assets/Lumina.svg",
//         rating: 3,
//         popularity: 23,
//         DateOpened: new Date(2020, 8, 19),
//         openingHour: [[{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }]],
//         dishes: [dishes[0], dishes[2]]
//     },
//     {
//         name: "Tiger Lilly",
//         chef: "Ran Shmueli",
//         imageURI: "/assets/restaurant-assets/tiger-lily.svg",
//         rating: 3,
//         popularity: 24,
//         DateOpened: new Date(2019, 10, 17),
//         openingHour: [[{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 22, minutes: 20 }]],
//         dishes: [dishes[0], dishes[4]]
//     },
//     {
//         name: "Onza",
//         chef: "Yossi Shitrit",
//         imageURI: "/assets/restaurant-assets/Onza.svg",
//         rating: 4,
//         popularity: 27,
//         DateOpened: new Date(2020, 7, 13),
//         openingHour: [[{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }],
//         [{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }],
//         [{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }],
//         [{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }],
//         [{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }],
//         [{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }],
//         [{ hours: 2, minutes: 18 }, { hours: 17, minutes: 20 }]],
//         dishes: [dishes[1]]
//     },
//     {
//         name: "Kitchen Market",
//         chef: "Yossi Shitrit",
//         imageURI: "/assets/restaurant-assets/kitchen-market.svg",
//         rating: 4,
//         popularity: 21,
//         DateOpened: new Date(2023, 1, 1),
//         openingHour: [[{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 10, minutes: 20 }]],
//         dishes: [dishes[2], dishes[1]]
//     },
//     {
//         name: "Mashya",
//         chef: "Yossi Shitrit",
//         imageURI: "/assets/restaurant-assets/Mashya.svg",
//         rating: 4,
//         popularity: 20,
//         DateOpened: new Date(2022, 2, 21),
//         openingHour: [[{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }],
//         [{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }],
//         [{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }],
//         [{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }],
//         [{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }],
//         [{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }],
//         [{ hours: 16, minutes: 20 }, { hours: 19, minutes: 20 }]],
//         dishes: [dishes[3]]
//     },
//     {
//         name: 'Kab Kem',
//         imageURI: "/assets/restaurant-assets/Kabkem.svg",
//         chef: 'Yariv Malili',
//         rating: 1,
//         popularity: 30,
//         DateOpened: new Date(2020, 5, 15),
//         openingHour: [[{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }],
//         [{ hours: 1, minutes: 20 }, { hours: 10, minutes: 20 }]],
//         dishes: [dishes[4]]
//     },
//     {
//         name: 'Messa',
//         imageURI: "/assets/restaurant-assets/Messa.svg",
//         chef: 'Aviv Moshe',
//         rating: 4,
//         popularity: 40,
//         DateOpened: new Date(2021, 1, 25),
//         openingHour: [[{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }],
//         [{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }],
//         [{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }],
//         [{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }],
//         [{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }],
//         [{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }],
//         [{ hours: 13, minutes: 20 }, { hours: 14, minutes: 20 }]],
//         dishes: [dishes[1]]
//     },
//     {
//         name: 'Nitan Thai',
//         imageURI: "/assets/restaurant-assets/nithan-thai.svg",
//         chef: 'shahf Shabtai',
//         rating: 1,
//         popularity: 35,
//         DateOpened: new Date(2018, 10, 5),
//         openingHour: [[{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 20, minutes: 20 }, { hours: 23, minutes: 20 }]],
//         dishes: [dishes[0]]
//     },
//     {
//         name: 'Ya Pan',
//         imageURI: "/assets/restaurant-assets/Yapan.svg",
//         chef: 'Yariv Malili',
//         rating: 1,
//         popularity: 25,
//         DateOpened: new Date(2022, 5, 2),
//         openingHour: [[{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],
//         [{ hours: 9, minutes: 20 }, { hours: 12, minutes: 20 }],],
//         dishes: [dishes[2]]
//     },
//     {
//         name: 'Malka',
//         imageURI: '/assets/restaurant-assets/malka.svg',
//         chef: 'Eyal Shani',
//         rating: 4,
//         popularity: 29,
//         DateOpened: new Date(2022, 1, 29),
//         openingHour: [[{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],
//         [{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],
//         [{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],
//         [{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],
//         [{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],
//         [{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],
//         [{ hours: 12, minutes: 45 }, { hours: 14, minutes: 55 }],],
//         dishes: [dishes[4], dishes[1]]
//     },
//     {
//         name: 'Machneyuda',
//         imageURI: "/assets/restaurant-assets/Machneyuda.svg",
//         chef: 'Assaf Granit',
//         rating: 3,
//         popularity: 24,
//         DateOpened: new Date(2022, 10, 20),
//         openingHour: [[{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],
//         [{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],
//         [{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],
//         [{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],
//         [{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],
//         [{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],
//         [{ hours: 18, minutes: 18 }, { hours: 21, minutes: 20 }],],
//         dishes: [dishes[3], dishes[1], dishes[0]]
//     },
//     {
//         name: 'TYO',
//         imageURI: "/assets/restaurant-assets/tyo.svg",
//         chef: 'Yama San',
//         rating: 4,
//         popularity: 40,
//         DateOpened: new Date(2021, 4, 25),
//         openingHour: [[{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],
//         [{ hours: 22, minutes: 20 }, { hours: 23, minutes: 20 }],],
//         dishes: [dishes[3]]
//     },
// ]